# Language (en, de, it, ru, tr)
language: en

# Allow to colorize damaged items
allowDamagedItems: false

# Allow to colorize enchanted items
allowEnchantedItems: false

# Keep Enchantments and RepairCosts
# (only used if allowEnchantedItems is true)
keepEnchantments: false

# Keep Item Title
keepTitle: false

# Keep Item Lore
keepLore: false